In [72]:
import numpy as np
from numpy.linalg import eig
from numpy.linalg import norm

data = open('pageRank-gr0.California.txt', 'r')

#data = open('C:/Users/Mithushan/Desktop/Pagerank/Pagerank/pageRank-gr0.California.txt', 'r')

a = True
edge_list = np.empty((16150, 2), dtype=int)
i = 0
M=np.zeros((9664,9664), dtype=float) # 9663 total nodes, create empty matrix to store edge relationships


In [73]:
# California dataset
# Reading data and creating edge list
while a:
    data_line = data.readline()
    if not data_line:
        print("eof")
        a = False
        break
    if data_line[0] == 'e':
        t = data_line.split()
        edge_list[i][0] = t[1]
        edge_list[i][1] = t[2]
        i = i + 1


# Creating link matrix, binary
for i in range(len(edge_list)):
    M[edge_list[i][1]][edge_list[i][0]] = 1

column_sum = M.sum(axis=0)



# To prevent division with 0
for x in range(len(column_sum)):
    if column_sum[x] == 0:
        column_sum[x] = 1

# Make matrix column stochastic
Mt=M.T
column_sum_t = column_sum.T
Mt = Mt/column_sum_t
Q=Mt.T



eof


In [74]:
print(np.linalg.norm(Q,ord=1))

# Q = np.zeros((6,6))

# Q[0,1] =1/3
# Q[1,0] =1/3
# Q[2,1] =1/3
# Q[2,4] =1/3
# Q[2,5] =1/2
# Q[3,0] =1/3
# Q[3,4] =1/3
# Q[4,0] =1/3
# Q[4,1] =1/3
# Q[4,5] =1/2
# Q[5,2] =1
# Q[5,4] =1/3
# print(Q)


157.62916666666666


In [75]:
epsilon = 10e-5
residual = 1

z = np.ones(Q.shape[1]) / (Q.shape[1])
v = np.ones(Q.shape[1]) / (Q.shape[1])
alpha = 0.55
epsilon = 10e-4
res = 1

while res > epsilon:
    yhat = alpha * np.matmul(Q, z)
    beta = 1 - np.linalg.norm(yhat, ord=1)
    y = yhat + beta * v
    res = np.linalg.norm(y - z, ord=1)
    z=y
    print(y)
    print('Residual=', res)

print(y)


[4.53974460e-04 3.38997709e-03 5.11249927e-05 ... 3.21542422e-05
 3.21542422e-05 3.21542422e-05]
Residual= 1.1253650159916706
[2.82015754e-04 1.65207325e-03 7.72165244e-05 ... 6.08876672e-05
 6.08876672e-05 6.08876672e-05]
Residual= 0.6332364016127565
[3.78677287e-04 2.70483587e-03 6.57313784e-05 ... 5.03699780e-05
 5.03699780e-05 5.03699780e-05]
Residual= 0.27085959938815396
[3.46141367e-04 2.25211814e-03 6.98148910e-05 ... 5.36176421e-05
 5.36176421e-05 5.36176421e-05]
Residual= 0.10252068140035206
[3.60146024e-04 2.46283101e-03 6.83135019e-05 ... 5.26301575e-05
 5.26301575e-05 5.26301575e-05]
Residual= 0.03651227537819462
[3.56127248e-04 2.37907549e-03 6.87309555e-05 ... 5.28590364e-05
 5.28590364e-05 5.28590364e-05]
Residual= 0.012635060415184229
[3.57519302e-04 2.41345533e-03 6.85953820e-05 ... 5.28069825e-05
 5.28069825e-05 5.28069825e-05]
Residual= 0.004347805192881456
[3.57189321e-04 2.40022343e-03 6.86151225e-05 ... 5.28036803e-05
 5.28036803e-05 5.28036803e-05]
Residual= 0.00

In [76]:
import string
file2 = open('text_california.txt','w')
for i in y:
    my_str=str(i)
    file2.write(my_str+'\n')
file2.close()

In [77]:
#still problem with web-stanford dataset but we now are able to create a spars matrix with california data set

In [85]:
# Stanford dataset
import numpy as np
from numpy.linalg import eig
from numpy.linalg import norm
from scipy.sparse import csc_matrix
from scipy.sparse import csr_matrix
from scipy.sparse import coo_matrix

# data = open('web-stanford.txt', 'r')

data = open('pageRank-gr0.California.txt', 'r')

#edge_list_2 = np.empty((2312497, 2),dtype=int)
edge_list_2 = np.empty((16150, 2),dtype=int)

# Initializing coordinate vectors for sparse matrix
# row = np.empty(2312497,dtype=int)
# col = np.empty(2312497,dtype=int)
# m_data = np.empty(2312497,dtype=int)

row = np.empty(16150,dtype=int)
col = np.empty(16150,dtype=int)
m_data = np.empty(16150,dtype=int)

print(np.shape(col))
print(np.shape(row))
print(np.shape(m_data))


(16150,)
(16150,)
(16150,)


In [86]:
from numpy.linalg import norm
from scipy.sparse import csc_matrix
from scipy.sparse import csr_matrix
from scipy.sparse import coo_matrix

# data = open('web-stanford.txt', 'r')

data = open('C:/Users/Mithushan/Desktop/Pagerank/Pagerank/pageRank-gr0.California.txt', 'r')

#edge_list_2 = np.empty((2312497, 2),dtype=int)
edge_list_2 = np.empty((16150, 2),dtype=int)

# Initializing coordinate vectors for sparse matrix
# row = np.empty(2312497,dtype=int)
# col = np.empty(2312497,dtype=int)
# m_data = np.empty(2312497,dtype=int)

row = np.empty(16150,dtype=int)
col = np.empty(16150,dtype=int)
m_data = np.empty(16150,dtype=int)


In [87]:
# Stanford dataset
# Reading data and creating edge list
a = True
i = 0
while a:
    data_line = data.readline()
    if not data_line:
        print("eof")
        a = False
        break
    # if data_line[0] != '#':
    #     t = data_line.split()
    #     edge_list_2[i][0] = int(t[0])
    #     edge_list_2[i][1] = int(t[1])
    #     i = i + 1
    if data_line[0] == 'e':
        t = data_line.split()
        edge_list_2[i][0] = int(t[1])
        edge_list_2[i][1] = int(t[2])
        i = i + 1


eof


In [88]:

# Creating sparse link matrix, binary
for i in range(len(edge_list_2)):
    col[i] = edge_list_2[i][0]
    row[i] = edge_list_2[i][1]
    m_data[i] = 1


print(row.max())
print(col.max())

9634
9663


In [89]:

Q = coo_matrix((m_data, (row, col)),dtype=np.int8, shape=(9664, 9664)).toarray()
print(Q)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [90]:
column_sum = M.sum(axis=0)

# To prevent division with 0
for x in range(len(column_sum)):
    if column_sum[x] == 0:
        column_sum[x] = 1

# Make matrix column stochastic
Mt=M.T
column_sum_t = column_sum.T
Mt = Mt/column_sum_t
Q=Mt.T

print(Q)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
