In [24]:
# tiny dataset
import numpy as np
from numpy.linalg import eig
from numpy.linalg import norm
from scipy.sparse import csr_matrix


#[ 0    1/3  0  0  0    0]
#  1/3  0    0  0  0    0
#  0    1/3  0  0  1/3  1/2
#  1/3  0    0  0  1/3  0
#  1/3  1/3  0  0  0    1/2
#  0    0    1  0  1/3  0

M=np.array([[ 0, 1, 0, 0, 0, 0],
            [ 1, 0, 0, 0, 0, 0],
            [ 0, 1, 0, 0, 1, 1],
            [ 1, 0, 0, 0, 1, 0],
            [ 1, 1, 0, 0, 0, 1],
            [ 0, 0, 1, 0, 1, 0]])

Q=csr_matrix(M)




In [25]:

c_sum=Q.sum(axis=0)
csr_sum=csr_matrix(c_sum, dtype=float)
print(type(csr_sum))
print(csr_sum)
print(csr_sum.data)


<class 'scipy.sparse.csr.csr_matrix'>
  (0, 0)	3.0
  (0, 1)	3.0
  (0, 2)	1.0
  (0, 4)	3.0
  (0, 5)	2.0
[3. 3. 1. 3. 2.]


In [26]:
for x in range(len(csr_sum.data)):
        csr_sum.data[x]=1/csr_sum.data[x]

print(csr_sum)

  (0, 0)	0.3333333333333333
  (0, 1)	0.3333333333333333
  (0, 2)	1.0
  (0, 4)	0.3333333333333333
  (0, 5)	0.5


In [27]:

Q=Q.multiply(csr_sum)
print(Q.toarray())
print(Q)

[[0.         0.33333333 0.         0.         0.         0.        ]
 [0.33333333 0.         0.         0.         0.         0.        ]
 [0.         0.33333333 0.         0.         0.33333333 0.5       ]
 [0.33333333 0.         0.         0.         0.33333333 0.        ]
 [0.33333333 0.33333333 0.         0.         0.         0.5       ]
 [0.         0.         1.         0.         0.33333333 0.        ]]
  (0, 1)	0.3333333333333333
  (1, 0)	0.3333333333333333
  (2, 5)	0.5
  (2, 4)	0.3333333333333333
  (2, 1)	0.3333333333333333
  (3, 4)	0.3333333333333333
  (3, 0)	0.3333333333333333
  (4, 5)	0.5
  (4, 1)	0.3333333333333333
  (4, 0)	0.3333333333333333
  (5, 4)	0.3333333333333333
  (5, 2)	1.0


In [36]:
epsilon = 10e-5
residual = 1
z = np.ones((6,1),Q.shape[1]) / (Q.shape[1])
v = np.ones(Q.shape[1]) / (Q.shape[1])
print(z.shape)
print(z.T.shape)


alpha = 0.85
epsilon = 10e-3
res = 1


TypeError: Cannot interpret '6' as a data type

In [34]:
print(Q.todense()*z.T)

ValueError: shapes (6,6) and (1,6) not aligned: 6 (dim 1) != 1 (dim 0)

In [ ]:

while res > epsilon:
    yhat=csr_matrix.dot(Q, z)
    #yhat =  Q.multiply(z)
    print(yhat)
    beta = 1 - np.linalg.norm(yhat, ord=1)
    y = yhat + beta * v
    res = np.linalg.norm(y - z, ord=1)
    z=y
    print(y)
    print('Residual=', res)

print(y)


In [30]:
print(Q.toarray())

[[0.         0.33333333 0.         0.         0.         0.        ]
 [0.33333333 0.         0.         0.         0.         0.        ]
 [0.         0.33333333 0.         0.         0.33333333 0.5       ]
 [0.33333333 0.         0.         0.         0.33333333 0.        ]
 [0.33333333 0.33333333 0.         0.         0.         0.5       ]
 [0.         0.         1.         0.         0.33333333 0.        ]]


In [31]:
Au=csr_matrix.dot(csr_matrix.transpose(Q),Q)
Hu=csr_matrix.dot(Q,csr_matrix.transpose(Q))
a=np.ones(Q.shape[0])
h=np.ones(Q.shape[0])
print(a,h)
for j in range(5):
    a=csr_matrix.dot(a,Au)
    a=a/sum(a)
    h=csr_matrix.dot(h,Hu)
    h=h/sum(h)
    print(a,h)

[1. 1. 1. 1. 1. 1.] [1. 1. 1. 1. 1. 1.]
[0.13978495 0.17204301 0.25806452 0.         0.20430108 0.22580645] [0.06666667 0.06666667 0.23333333 0.13333333 0.23333333 0.26666667]
[0.11702718 0.15862451 0.30282862 0.         0.21020521 0.21131448] [0.05734767 0.04659498 0.23835125 0.11469534 0.21684588 0.32616487]
[0.10495439 0.14545965 0.33970526 0.         0.21577544 0.19410526] [0.05287484 0.03900906 0.22860048 0.10907746 0.19754114 0.37289702]
[0.09662594 0.13380443 0.3700856  0.         0.22057386 0.17891018] [0.04848655 0.0349848  0.21746433 0.10690994 0.18052398 0.41163041]
[0.09023758 0.12412505 0.39476702 0.         0.22452811 0.16634223] [0.04460148 0.03220865 0.20758119 0.10573327 0.16626521 0.44361022]
