In [143]:
# tiny dataset
import numpy as np
from numpy.linalg import eig
from numpy.linalg import norm
from scipy.sparse import csr_matrix


#[ 0    1/3  0  0  0    0]
#  1/3  0    0  0  0    0
#  0    1/3  0  0  1/3  1/2
#  1/3  0    0  0  1/3  0
#  1/3  1/3  0  0  0    1/2
#  0    0    1  0  1/3  0

M=np.array([[ 0, 1, 0, 0, 0, 0],
            [ 1, 0, 0, 0, 0, 0],
            [ 0, 1, 0, 0, 1, 1],
            [ 1, 0, 0, 0, 1, 0],
            [ 1, 1, 0, 0, 0, 1],
            [ 0, 0, 1, 0, 1, 0]])

Q=csr_matrix(M)




In [144]:

c_sum=Q.sum(axis=0)
csr_sum=csr_matrix(c_sum, dtype=float)
print(type(csr_sum))
print(csr_sum)
print(csr_sum.data)


<class 'scipy.sparse.csr.csr_matrix'>
  (0, 0)	3.0
  (0, 1)	3.0
  (0, 2)	1.0
  (0, 4)	3.0
  (0, 5)	2.0
[3. 3. 1. 3. 2.]


In [145]:
for x in range(len(csr_sum.data)):
        csr_sum.data[x]=1/csr_sum.data[x]

print(csr_sum)

  (0, 0)	0.3333333333333333
  (0, 1)	0.3333333333333333
  (0, 2)	1.0
  (0, 4)	0.3333333333333333
  (0, 5)	0.5


In [146]:

Q=Q.multiply(csr_sum)
print(Q.toarray())
print(Q)

[[0.         0.33333333 0.         0.         0.         0.        ]
 [0.33333333 0.         0.         0.         0.         0.        ]
 [0.         0.33333333 0.         0.         0.33333333 0.5       ]
 [0.33333333 0.         0.         0.         0.33333333 0.        ]
 [0.33333333 0.33333333 0.         0.         0.         0.5       ]
 [0.         0.         1.         0.         0.33333333 0.        ]]
  (0, 1)	0.3333333333333333
  (1, 0)	0.3333333333333333
  (2, 5)	0.5
  (2, 4)	0.3333333333333333
  (2, 1)	0.3333333333333333
  (3, 4)	0.3333333333333333
  (3, 0)	0.3333333333333333
  (4, 5)	0.5
  (4, 1)	0.3333333333333333
  (4, 0)	0.3333333333333333
  (5, 4)	0.3333333333333333
  (5, 2)	1.0


In [200]:
epsilon = 10e-5
residual = 1
z = np.ones(Q.shape[1]) / (Q.shape[1])
v = np.ones(Q.shape[1]) / (Q.shape[1])
print(z.shape)
print(z.T.shape)


alpha = 0.85
epsilon = 10e-14
res = 1


(6,)
(6,)


In [201]:

while res > epsilon:
    yhat=csr_matrix.dot(Q, z)
    #yhat =  Q.multiply(z)
    #print(yhat)
    beta = 1 - np.linalg.norm(yhat, ord=1)
    y = yhat + beta * v
    res = np.linalg.norm(y - z, ord=1)
    z=y
    print(y)
    print('Residual=', res)

print(y)

[0.08333333 0.08333333 0.22222222 0.13888889 0.22222222 0.25      ]
Residual= 0.3888888888888889
[0.05092593 0.05092593 0.25       0.125      0.2037037  0.31944444]
Residual= 0.19444444444444442
[0.03780864 0.03780864 0.2654321  0.10570988 0.21450617 0.33873457]
Residual= 0.09104938271604941
[0.03022119 0.03022119 0.27109053 0.10172325 0.21219136 0.35455247]
Residual= 0.042952674897119354
[0.02702761 0.02702761 0.27503429 0.09775806 0.21437757 0.35877486]
Residual= 0.020704732510288135
[0.02530221 0.02530221 0.27614883 0.0967614  0.21369885 0.36278649]
Residual= 0.010252343392775413
[0.02456097 0.02456097 0.27718717 0.09579392 0.21438829 0.36350868]
Residual= 0.004899929507697111
[0.02415264 0.02415264 0.27736975 0.09561541 0.21409398 0.36461558]
Residual= 0.002578962493014321
[0.02398678 0.02398678 0.27765923 0.09535144 0.21434545 0.36467031]
Residual= 0.0011913768120544177
[0.0238875  0.0238875  0.27767114 0.09533599 0.21421825 0.36499962]
Residual= 0.0006824476547018232
[0.02385183 